
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HIRTIH KUMAR C V
 */
public class LoginPage extends javax.swing.JFrame {
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        exit_RadioButton.setSelected(false);
        Login_RadioButton.setSelected(false);
        mail_textField.setText("@rajalakshmi.edu.in");
    }
    
    private void DecideRole(String User_id){
        tableGenerator access;
            if(User_id.endsWith("Hr")){
                setVisible(false);
                access = new tableGenerator();
                access.User_id = User_id;
                access.UIreference_user_id = "Hr";
                access.requestApprove_RadioButton.setVisible(false);
                access.setVisible(true);
            }
            else if(User_id.endsWith("Management")){
                setVisible(false);
                access = new tableGenerator();
                access.User_id = User_id;
                access.UIreference_user_id = "Management";
                access.positionCreate_MenuItem.setVisible(false);
                access.positionEdit_MenuItem.setVisible(false);
                access.positionDelete_MenuItem.setVisible(false);
                access.Request_Menu.setVisible(true);
                access.setVisible(true);
            }
            else if(User_id.endsWith("Depatement_head")){
                setVisible(false);
                access = new tableGenerator();
                access.User_id = User_id;
                access.UIreference_user_id = "Depatement_head";
                //access.Position_Menu.setVisible(false);
                access.positionCreate_MenuItem.setVisible(false);
                access.positionEdit_MenuItem.setVisible(false);
                access.positionDelete_MenuItem.setVisible(false);
                access.Recruitment_Menu.setVisible(false);
                access.requestApprove_RadioButton.setVisible(false);
                access.setVisible(true);
            }
            else if(User_id.equals("Guest")){
                setVisible(false);
                access = new tableGenerator();
                access.User_id = User_id;
                access.UIreference_user_id = "Guest";
                access.Request_Menu.setVisible(false);
                access.Recruitment_Menu.setVisible(false);
                access.positionCreate_MenuItem.setVisible(false);
                access.positionEdit_MenuItem.setVisible(false);
                access.positionDelete_MenuItem.setVisible(false);
                access.requestApprove_RadioButton.setVisible(false);
                access.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "ACCOUNT NOT FOUND");
            }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        mail_label = new javax.swing.JLabel();
        password_label = new javax.swing.JLabel();
        mail_textField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        Login_Button = new javax.swing.JButton();
        commonDisplay_label = new javax.swing.JLabel();
        Login_as_Guest_checkBox = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        shortCut_Menu = new javax.swing.JMenu();
        exit_RadioButton = new javax.swing.JRadioButtonMenuItem();
        Login_RadioButton = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        panel.setName("Login"); // NOI18N

        title_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title_label.setText("RECRUITMENT PORTAL SYSTEM");

        mail_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mail_label.setText("MAIL ID");

        password_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        password_label.setText("PASSCODE");

        mail_textField.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        mail_textField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mail_textFieldMouseClicked(evt);
            }
        });

        passwordField.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });

        Login_Button.setText("Log - in");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });

        commonDisplay_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        commonDisplay_label.setForeground(new java.awt.Color(255, 51, 51));

        Login_as_Guest_checkBox.setBackground(new java.awt.Color(255, 255, 255));
        Login_as_Guest_checkBox.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        Login_as_Guest_checkBox.setText("Log - in as Guest");
        Login_as_Guest_checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_as_Guest_checkBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(Login_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Login_as_Guest_checkBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password_label)
                                    .addComponent(mail_label))
                                .addGap(75, 75, 75)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mail_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(commonDisplay_label, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(title_label)
                        .addGap(133, 133, 133))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title_label)
                .addGap(49, 49, 49)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mail_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail_label))
                .addGap(46, 46, 46)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_label))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(Login_Button)
                        .addGap(18, 18, 18)
                        .addComponent(commonDisplay_label, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Login_as_Guest_checkBox)))
                .addContainerGap())
        );

        shortCut_Menu.setText("Shortcuts");

        exit_RadioButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit_RadioButton.setText("Exit");
        exit_RadioButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_RadioButtonActionPerformed(evt);
            }
        });
        shortCut_Menu.add(exit_RadioButton);

        Login_RadioButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        Login_RadioButton.setSelected(true);
        Login_RadioButton.setText("Login - in");
        Login_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_RadioButtonActionPerformed(evt);
            }
        });
        shortCut_Menu.add(Login_RadioButton);

        jMenuBar1.add(shortCut_Menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
        
        if(mail_textField.getText().endsWith("@rajalakshmi.edu.in") && passwordField.getPassword().length > 0){
            Mailid = mail_textField.getText().trim();
            Password = passwordField.getPassword();
            mail_textField.setText("@rajalakshmi.edu.in");
            passwordField.setText("");
            DataBaseHandler Connecter = new DataBaseHandler();
            User_id_status = Connecter.CheckForLoginPassword(Mailid , String.valueOf(Password));//Sends data to check whether mail and password exists are not
            System.out.println(User_id_status);
            if(!"false".equals(User_id_status)){
                DecideRole(User_id_status);
            }else{
                JOptionPane.showMessageDialog(null, "No such role exist (OR) Account not found");
            }
        }
        else{
            commonDisplay_label.setText("Invalid Credentials");
            commonDisplay_label.setVisible(true);
            passwordField.setText("");
        }
        
        
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void mail_textFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mail_textFieldMouseClicked
        
        commonDisplay_label.setVisible(false);
        
    }//GEN-LAST:event_mail_textFieldMouseClicked
    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        
        commonDisplay_label.setVisible(false);
        
    }//GEN-LAST:event_passwordFieldMouseClicked

    private void exit_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_RadioButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exit_RadioButtonActionPerformed

    private void Login_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_RadioButtonActionPerformed

        Login_ButtonActionPerformed(evt);

    }//GEN-LAST:event_Login_RadioButtonActionPerformed

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        
       
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        

        if(PasswordCount > 30){
           commonDisplay_label.setText("maximum of 30 Characters are allowed");
           commonDisplay_label.setVisible(true);
        }if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE){
            PasswordCount -= 1;
        }else if(passwordField.getPassword().length == 0){
            PasswordCount = 0;
        }else{
           PasswordCount += 1;
        }        
        
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void Login_as_Guest_checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_as_Guest_checkBoxActionPerformed

        DecideRole("Guest");

    }//GEN-LAST:event_Login_as_Guest_checkBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException error) {
            JOptionPane.showMessageDialog(null , "error while setting UI");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }
    
    private int PasswordCount;
    private String User_id_status;
    private String Mailid;
    private char Password[] = new char[30] ;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_Button;
    private javax.swing.JRadioButtonMenuItem Login_RadioButton;
    private javax.swing.JCheckBox Login_as_Guest_checkBox;
    private javax.swing.JLabel commonDisplay_label;
    private javax.swing.JRadioButtonMenuItem exit_RadioButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel mail_label;
    private javax.swing.JTextField mail_textField;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel password_label;
    private javax.swing.JMenu shortCut_Menu;
    private javax.swing.JLabel title_label;
    // End of variables declaration//GEN-END:variables
}
