

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HIRTIH KUMAR C V
 */


public class tableGenerator extends javax.swing.JFrame {
    
    /**
     * Creates new form tableGenerator
     */
    public tableGenerator() {
        initComponents();
        
        positionCreate_MenuItem.setSelected(false);
        positionEdit_MenuItem.setSelected(false);
        positionDelete_MenuItem.setSelected(false);
        requestCreate_MenuItem.setSelected(false);
        
        requestView_RadioButton.setSelected(false);
        requestApprove_RadioButton.setSelected(false);
        recruitementView_RadioButton.setSelected(false);
        shortcut_Logout_CheckBox.setSelected(false);
        formFillPanel.setVisible(false);
        
        PositionCount_spinner.getModel().setValue(1);
    }
    
    private void HrManagementFormFill(){
        formFillPanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        formFillPanel = new javax.swing.JPanel();
        Jobtitle_label = new javax.swing.JLabel();
        JobTitle_txtField = new javax.swing.JTextField();
        Experience_label = new javax.swing.JLabel();
        Experience_txtField = new javax.swing.JTextField();
        Qualifications_label = new javax.swing.JLabel();
        Skills_label = new javax.swing.JLabel();
        Qualifications_txtField = new javax.swing.JTextField();
        Skills_txtField = new javax.swing.JTextField();
        JobDescription_label = new javax.swing.JLabel();
        PositionCount_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JobDescription_txtArea = new javax.swing.JTextArea();
        PositionCount_spinner = new javax.swing.JSpinner();
        btCreate = new javax.swing.JButton();
        Departement_label = new javax.swing.JLabel();
        Departement_txtField = new javax.swing.JTextField();
        btCancel = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        Position_Menu = new javax.swing.JMenu();
        positionCreate_MenuItem = new javax.swing.JMenuItem();
        positionEdit_MenuItem = new javax.swing.JMenuItem();
        positionDelete_MenuItem = new javax.swing.JMenuItem();
        positionView_MenuItem = new javax.swing.JMenuItem();
        Request_Menu = new javax.swing.JMenu();
        requestCreate_MenuItem = new javax.swing.JMenuItem();
        requestView_RadioButton = new javax.swing.JRadioButtonMenuItem();
        requestApprove_RadioButton = new javax.swing.JRadioButtonMenuItem();
        Recruitment_Menu = new javax.swing.JMenu();
        recruitementView_RadioButton = new javax.swing.JRadioButtonMenuItem();
        LogOut_Menu = new javax.swing.JMenu();
        shortcut_Logout_CheckBox = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        Jobtitle_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Jobtitle_label.setText("Job Title");

        JobTitle_txtField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        Experience_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Experience_label.setText("Experience");

        Experience_txtField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        Qualifications_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Qualifications_label.setText("Qualifications");

        Skills_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Skills_label.setText("Skills");

        Qualifications_txtField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        Skills_txtField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        JobDescription_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        JobDescription_label.setText("Job Description");

        PositionCount_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        PositionCount_label.setText("Position Count");

        JobDescription_txtArea.setColumns(20);
        JobDescription_txtArea.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        JobDescription_txtArea.setRows(5);
        jScrollPane1.setViewportView(JobDescription_txtArea);

        PositionCount_spinner.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btCreate.setText("Create");
        btCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateActionPerformed(evt);
            }
        });

        Departement_label.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Departement_label.setText("Departement");

        Departement_txtField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formFillPanelLayout = new javax.swing.GroupLayout(formFillPanel);
        formFillPanel.setLayout(formFillPanelLayout);
        formFillPanelLayout.setHorizontalGroup(
            formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formFillPanelLayout.createSequentialGroup()
                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formFillPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JobDescription_label)
                            .addComponent(Qualifications_label)
                            .addComponent(Jobtitle_label))
                        .addGap(18, 18, 18)
                        .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formFillPanelLayout.createSequentialGroup()
                                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Qualifications_txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(JobTitle_txtField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Experience_label, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Skills_label, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Experience_txtField)
                                    .addComponent(Skills_txtField, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formFillPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formFillPanelLayout.createSequentialGroup()
                                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formFillPanelLayout.createSequentialGroup()
                                .addComponent(Departement_label)
                                .addGap(18, 18, 18)
                                .addComponent(Departement_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(PositionCount_label)
                                .addGap(18, 18, 18)
                                .addComponent(PositionCount_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formFillPanelLayout.setVerticalGroup(
            formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formFillPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobTitle_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jobtitle_label)
                    .addComponent(Experience_label)
                    .addComponent(Experience_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Qualifications_label)
                    .addComponent(Skills_label)
                    .addComponent(Qualifications_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Skills_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JobDescription_label)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PositionCount_label)
                    .addComponent(PositionCount_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Departement_label)
                    .addComponent(Departement_txtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formFillPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCreate)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(formFillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(formFillPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        Position_Menu.setText("Position");

        positionCreate_MenuItem.setText("Create");
        positionCreate_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionCreate_MenuItemActionPerformed(evt);
            }
        });
        Position_Menu.add(positionCreate_MenuItem);

        positionEdit_MenuItem.setText("Edit");
        positionEdit_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionEdit_MenuItemActionPerformed(evt);
            }
        });
        Position_Menu.add(positionEdit_MenuItem);

        positionDelete_MenuItem.setText("Delete");
        positionDelete_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionDelete_MenuItemActionPerformed(evt);
            }
        });
        Position_Menu.add(positionDelete_MenuItem);

        positionView_MenuItem.setText("View");
        positionView_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionView_MenuItemActionPerformed(evt);
            }
        });
        Position_Menu.add(positionView_MenuItem);

        jMenuBar2.add(Position_Menu);

        Request_Menu.setText("Request");

        requestCreate_MenuItem.setText("Create");
        requestCreate_MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestCreate_MenuItemActionPerformed(evt);
            }
        });
        Request_Menu.add(requestCreate_MenuItem);

        requestView_RadioButton.setSelected(true);
        requestView_RadioButton.setText("View");
        requestView_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestView_RadioButtonActionPerformed(evt);
            }
        });
        Request_Menu.add(requestView_RadioButton);

        requestApprove_RadioButton.setSelected(true);
        requestApprove_RadioButton.setText("Approve");
        requestApprove_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestApprove_RadioButtonActionPerformed(evt);
            }
        });
        Request_Menu.add(requestApprove_RadioButton);

        jMenuBar2.add(Request_Menu);

        Recruitment_Menu.setText("Recruitement");

        recruitementView_RadioButton.setSelected(true);
        recruitementView_RadioButton.setText("View");
        recruitementView_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recruitementView_RadioButtonActionPerformed(evt);
            }
        });
        Recruitment_Menu.add(recruitementView_RadioButton);

        jMenuBar2.add(Recruitment_Menu);

        LogOut_Menu.setText("Log - out");

        shortcut_Logout_CheckBox.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        shortcut_Logout_CheckBox.setSelected(true);
        shortcut_Logout_CheckBox.setText("Log - out");
        shortcut_Logout_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shortcut_Logout_CheckBoxActionPerformed(evt);
            }
        });
        LogOut_Menu.add(shortcut_Logout_CheckBox);

        jMenuBar2.add(LogOut_Menu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestView_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestView_RadioButtonActionPerformed
        try {
            if(formFillPanel.isEnabled()){
                formFillPanel.setVisible(false);
            }
            SelectSQl = "requestView";
            access = new displayTable();
            access.UIreference_user_id = UIreference_user_id;
            access.setVisible(true);
            access.receiveData(SelectSQl,"request_id","department","job_title","experience","Qualifications","Skills","JobDescription","PositionCount","user_id","request_status","time_stamp");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null , "SQLException occured");
        }
 
    }//GEN-LAST:event_requestView_RadioButtonActionPerformed

    private void requestCreate_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestCreate_MenuItemActionPerformed
        
        SelectSQl = "Request created";
        HrManagementFormFill();
        
    }//GEN-LAST:event_requestCreate_MenuItemActionPerformed

    private void btCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateActionPerformed
        String Department , JobTitle , Experience , Qualifications , Skills , JobDescription , Message , InitialRequestStatus , Status[] = new String[2];
        int PositionCount;
        
        JobTitle = JobTitle_txtField.getText().trim();
        Experience = String.valueOf(Experience_txtField.getText().trim());
        if(Experience.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter the experience required in number");
        }
        Qualifications = String.valueOf(Qualifications_txtField.getText().trim());
        Skills = Skills_txtField.getText().trim();
        Department = Departement_txtField.getText().trim();
        JobDescription = String.valueOf(JobDescription_txtArea.getText().trim());
        PositionCount = (int) PositionCount_spinner.getModel().getValue();
        InitialRequestStatus = SelectSQl.equals("Position created") ?  "In progress" : "Pending Approval";
        Connector = new DataBaseHandler();
        
        try{
            Status = Connector.InsertNewAccountData(Department,JobTitle,Experience,Qualifications,Skills,JobDescription,PositionCount,User_id,InitialRequestStatus,SelectSQl).split("-");
            System.out.println("Staus : " + java.util.Arrays.toString(Status));
            if(!Status.equals("Not able to update request") || !Status.equals("SQLException has occured while Updating request")){
                Message = ""+SelectSQl+"successfully! " + " UniqueID : "+ Status[0] +" Status : " + Status[1] +"";
                JOptionPane.showMessageDialog(null,Message);
                formFillPanel.setVisible(false);
            }
        }catch(HeadlessException ex){
                JOptionPane.showMessageDialog(null,"Not able to update request");
        }
        
    }//GEN-LAST:event_btCreateActionPerformed

    private void positionCreate_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionCreate_MenuItemActionPerformed

        SelectSQl = "Position created";
        HrManagementFormFill();
        
    }//GEN-LAST:event_positionCreate_MenuItemActionPerformed

    private void positionView_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionView_MenuItemActionPerformed

        try {
            SelectSQl = "positionView";
            access = new displayTable();
            access.UIreference_user_id = UIreference_user_id;
            access.setVisible(true);
            access.receiveData(SelectSQl, "position_id","department","job_title","experience","Qualifications","Skills","JobDescription","PositionCount","user_id","position_status","time_stamp");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null , "SQLException occured");
        }
        
    }//GEN-LAST:event_positionView_MenuItemActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
       
        JobTitle_txtField.setText("");
        Experience_txtField.setText("");
        Qualifications_txtField.setText("");
        Skills_txtField.setText("");
        Departement_txtField.setText("");
        JobDescription_txtArea.setText("");
        PositionCount_spinner.getModel().setValue(1);
        formFillPanel.setVisible(false);
        
    }//GEN-LAST:event_btCancelActionPerformed

    private void positionEdit_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionEdit_MenuItemActionPerformed

        try {
            SelectSQl = "Edit";
            Connector = new DataBaseHandler();
            access = new displayTable();
            access.UIreference_user_id = UIreference_user_id;
            access.setVisible(true);
            access.receiveData(SelectSQl ,"position_id","department","job_title","experience","Qualifications","Skills","JobDescription","PositionCount","user_id","position_status","time_stamp");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null , "SQLException occured");
        }

        
    }//GEN-LAST:event_positionEdit_MenuItemActionPerformed

    private void positionDelete_MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionDelete_MenuItemActionPerformed

        try {
            SelectSQl = "Delete";
            access = new displayTable();
            access.UIreference_user_id = UIreference_user_id;
            access.setVisible(true);
            access.receiveData(SelectSQl, "position_id","department","job_title","experience","Qualifications","Skills","JobDescription","PositionCount","user_id","position_status","time_stamp");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null , "SQLException occured");
        }
    }//GEN-LAST:event_positionDelete_MenuItemActionPerformed

    private void requestApprove_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestApprove_RadioButtonActionPerformed
        try {
            SelectSQl = "Management Approval";
            access = new displayTable();
            access.UIreference_user_id = UIreference_user_id;
            access.setVisible(true);
            access.receiveData(SelectSQl, "request_id","department","job_title","experience","Qualifications","Skills","JobDescription","PositionCount","user_id","request_status","time_stamp");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null , "SQLException occured");
        }
    }//GEN-LAST:event_requestApprove_RadioButtonActionPerformed

    private void recruitementView_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recruitementView_RadioButtonActionPerformed
        
        
        try {
            SelectSQl = "Recruitement View";
            access = new displayTable();
            access.UIreference_user_id = UIreference_user_id;
            access.setVisible(true);
            access.receiveData(SelectSQl, "sr_no","position_id","job_title","file","user_id","recruitement_status","time_stamp");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null , "SQLException occured");
        }   
        

    }//GEN-LAST:event_recruitementView_RadioButtonActionPerformed

    private void shortcut_Logout_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortcut_Logout_CheckBoxActionPerformed

        this.dispose();
        new LoginPage().setVisible(true);
        
        
    }//GEN-LAST:event_shortcut_Logout_CheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the 'Windows' look and feel */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null , "error while setting UI");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new tableGenerator().setVisible(true);
            }
        });
    }
    
    private displayTable access ;
    protected String SelectSQl;
    public DataBaseHandler Connector;
    protected String User_id , UIreference_user_id;
    protected String checkForEditDelete;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Departement_label;
    private javax.swing.JTextField Departement_txtField;
    private javax.swing.JLabel Experience_label;
    private javax.swing.JTextField Experience_txtField;
    private javax.swing.JLabel JobDescription_label;
    private javax.swing.JTextArea JobDescription_txtArea;
    private javax.swing.JTextField JobTitle_txtField;
    private javax.swing.JLabel Jobtitle_label;
    private javax.swing.JMenu LogOut_Menu;
    private javax.swing.JLabel PositionCount_label;
    private javax.swing.JSpinner PositionCount_spinner;
    protected javax.swing.JMenu Position_Menu;
    private javax.swing.JLabel Qualifications_label;
    private javax.swing.JTextField Qualifications_txtField;
    protected javax.swing.JMenu Recruitment_Menu;
    protected javax.swing.JMenu Request_Menu;
    private javax.swing.JLabel Skills_label;
    private javax.swing.JTextField Skills_txtField;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btCreate;
    private javax.swing.JPanel formFillPanel;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    protected javax.swing.JMenuItem positionCreate_MenuItem;
    protected javax.swing.JMenuItem positionDelete_MenuItem;
    protected javax.swing.JMenuItem positionEdit_MenuItem;
    protected javax.swing.JMenuItem positionView_MenuItem;
    private javax.swing.JRadioButtonMenuItem recruitementView_RadioButton;
    protected javax.swing.JRadioButtonMenuItem requestApprove_RadioButton;
    private javax.swing.JMenuItem requestCreate_MenuItem;
    private javax.swing.JRadioButtonMenuItem requestView_RadioButton;
    private javax.swing.JCheckBoxMenuItem shortcut_Logout_CheckBox;
    // End of variables declaration//GEN-END:variables
}
